version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: series_tracker
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 5s
      retries: 10

  backend:
    build:
      context: ./backend  # Asegura que Docker busque el Dockerfile en backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080

volumes:
  db_data:
