version: '3.8'
services:
  db:
    build: .
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ../backend
    container_name: go_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=seriesdb
    restart: unless-stopped

volumes:
  mysql_data:
